version: '3'

services:
  django:
    build: .
    command: python bin/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  gunicorn:
    build: .
    command: gunicorn back_core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "90:90"
    depends_on:
      - gunicorn

  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres


volumes:
  static:
  postgres_data: