# Generated by Django 4.2 on 2023-04-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('created_at', models.DateField(auto_now=True)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='estudianteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('ciudad', models.CharField(choices=[('Colombia', 'Colombia'), ('Estados Unidos', 'EEUU'), ('Espana', 'España'), ('Mexico', 'Mexico'), ('Peru', 'Peru'), ('Canada', 'Canada'), ('Inglaterra', 'Inglaterra'), ('Italia', 'Italia'), ('Venezuela', 'Venezuela'), ('Chile', 'Chile'), ('Panama', 'Panama')], default='Colombia', max_length=14)),
                ('telefono', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudent_curso', to='administration_sc.cursomodel')),
            ],
        ),
        migrations.CreateModel(
            name='profesorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('area_especializacion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=15)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_teacher', to='administration_sc.cursomodel')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudent_teacher', to='administration_sc.estudiantemodel')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_teacher', to='administration_sc.profesormodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_estudent', to='administration_sc.estudiantemodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_teacher', to='administration_sc.profesormodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='valoraciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_estudent_vc', to='administration_sc.estudiantemodel'),
        ),
    ]
