# Generated by Django 4.2 on 2023-04-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('categoria', models.CharField(blank=True, choices=[('Academico', 'Academico'), ('Tecnologico', 'Tecnologico')], default='Academico', max_length=11)),
                ('nivel_curso', models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=11)),
                ('numero_max_estudiantes', models.IntegerField(blank=True, null=True)),
                ('codigo_curso', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateField(auto_now=True)),
                ('estado', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estudianteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('ciudad', models.CharField(choices=[('Colombia', 'Colombia'), ('Estados Unidos', 'EEUU'), ('Espana', 'España'), ('Mexico', 'Mexico'), ('Peru', 'Peru'), ('Canada', 'Canada'), ('Inglaterra', 'Inglaterra'), ('Italia', 'Italia'), ('Venezuela', 'Venezuela'), ('Chile', 'Chile'), ('Panama', 'Panama')], default='Colombia', max_length=14)),
                ('telefono', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('contrasena', models.CharField(blank=True, max_length=200, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('cursos', models.ManyToManyField(to='administration_sc.cursomodel')),
            ],
        ),
        migrations.CreateModel(
            name='profesorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('area_especializacion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=15)),
                ('contrasena', models.CharField(blank=True, max_length=200, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('cursos', models.ManyToManyField(to='administration_sc.cursomodel')),
                ('estudiantes', models.ManyToManyField(to='administration_sc.estudiantemodel')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='profesores',
            field=models.ManyToManyField(to='administration_sc.profesormodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='estudiantes',
            field=models.ManyToManyField(to='administration_sc.estudiantemodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='profesores',
            field=models.ManyToManyField(to='administration_sc.profesormodel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='valoraciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_estudent_vc', to='administration_sc.estudiantemodel'),
        ),
    ]
