# Generated by Django 4.2 on 2023-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantemodel',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.cursomodel'),
        ),
        migrations.AlterField(
            model_name='estudiantemodel',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.profesormodel'),
        ),
    ]
