# Generated by Django 4.2.2 on 2023-07-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='estudiantemodel',
            name='telefono',
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='departments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='email_unique',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='identificacion_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='number_document',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='password',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='estudiantemodel',
            name='type_document',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
