# Generated by Django 4.2 on 2023-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomodel',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Academico', 'Academico'), ('Tecnologico', 'Tecnologico')], default='Academico', max_length=11),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='codigo_curso',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='nivel_curso',
            field=models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=11),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='numero_max_estudiantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
