# Generated by Django 4.2 on 2023-04-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0002_cursomodel_categoria_cursomodel_codigo_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursomodel',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_estudent', to='administration_sc.estudiantemodel'),
        ),
        migrations.AlterField(
            model_name='cursomodel',
            name='id_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_teacher', to='administration_sc.profesormodel'),
        ),
        migrations.AlterField(
            model_name='estudiantemodel',
            name='id_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudent_curso', to='administration_sc.cursomodel'),
        ),
        migrations.AlterField(
            model_name='estudiantemodel',
            name='id_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_teacher', to='administration_sc.profesormodel'),
        ),
        migrations.AlterField(
            model_name='profesormodel',
            name='id_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_teacher', to='administration_sc.cursomodel'),
        ),
        migrations.AlterField(
            model_name='profesormodel',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudent_teacher', to='administration_sc.estudiantemodel'),
        ),
    ]
