# Generated by Django 4.2 on 2023-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0002_alter_estudiantemodel_cursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursomodel',
            name='profesores',
        ),
    ]
