# Generated by Django 4.2 on 2023-04-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0003_alter_cursomodel_id_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantemodel',
            name='contrasena',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
