# Generated by Django 4.2 on 2023-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0004_cursomodel_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursomodel',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.estudiantemodel'),
        ),
        migrations.AlterField(
            model_name='cursomodel',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.profesormodel'),
        ),
        migrations.AlterField(
            model_name='profesormodel',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.cursomodel'),
        ),
        migrations.AlterField(
            model_name='profesormodel',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, to='administration_sc.estudiantemodel'),
        ),
    ]
