# Generated by Django 4.2 on 2023-04-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0006_profesormodel_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantemodel',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profesormodel',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
