# Generated by Django 4.2 on 2023-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_sc', '0006_profesormodel_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
